### ISSUE TITLE
Unable to generate csv file

### ISSUE THREAD

**Issue by akiefs** [microsoft/FHIR-Analytics-Pipelines#287] opened 2023-01-31 08:11 UTC
Hi,

We are in process of deploying FHIR to CDM accelerator. We have followed the steps mentioned to export the data from Azure API for FHIR to storage account in CSV format. But it is not generating csv files. We can see the ndjson files getting generated from "StartExportTask" from the ADF pipeline for each resources in FHIR. The ADF pipeline "egreess-pipeline" completes with no error. As mentioned in the document, if there is no files generated, to check in adfjobs folder in storage account. I checked the folder as well. There is stderr.txt files. But the files are empty. Please suggest.

Regards,
SAM

**Comment by tongwu-msft** [comment] 2023-02-03 08:42
It should be caused by configuration issue, could you use local tool to verify the configurations?

**Comment by moria97** [comment] 2023-02-23 07:37
Close it as no more activities in this thread.

**Closed by moria97** 2023-02-23 07:37 UTC
